name: 🚀 Auto Deploy to Contabo VPS

on:
  push:
    branches: [master]  # Change this to your branch if it's not main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout Code
      uses: actions/checkout@v3

    - name: 🔐 Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: 🚚 Push Code to VPS
      run: |
        git remote add live ssh://${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/root/myapi.git
        git push live main --force
